name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Install Maven 3.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y maven=3.9.2-*
      
      # Step to automatically bump the version number
      - name: Bump version
        id: bump_version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # Extract current version and bump patch version
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          major=$(echo $current_version | cut -d'.' -f1)
          minor=$(echo $current_version | cut -d'.' -f2)
          patch=$(echo $current_version | cut -d'.' -f3)
          new_version="${major}.${minor}.$((patch + 1))"
          
          # Set the new version in pom.xml
          mvn versions:set -DnewVersion=$new_version
          
          # Commit the updated version
          git add pom.xml
          git commit -m "Bump version to $new_version"
          git push
          
  build-and-push:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install Maven 3.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y maven=3.9.2-*

      - name: Build the jar
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Extract the new version from pom.xml
          new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/java-maven-app:$new_version .

      - name: Image pushed successfully
        run: echo "Docker image pushed with version $new_version."
